swagger: "2.0"
info:
  version: "1.0.0"
  title: Grocer X App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user/account/{id}/view:
    x-swagger-router-controller: users
    get:
      tags:
        - profile
      summary: Return user profile
      operationId: viewAccount
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Profile Object
          schema:
            properties:
              id:
                type: number
                example: 5000012
              firstName:
                type: string
                example: John
              lastName:
                type: string
                example: Stone
              dateBirthday:
                type: number
                example: 587260800000
                description: timestamp
              address1:
                type: string
                example: Upper Thompson Road
              address2:
                type: string
                example: East Cost Drive
        # 404:
        #   description: ofile not found
        #   schema:
        #     properties:
        #       message:
        #         type: string
        #         example: Not found
  /user/account/login:
    x-swagger-router-controller: users
    post:
      tags:
        - user
      summary: Return authenticated & authorized user
      operationId: loginAccount
      parameters:
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/UserLogin"
      responses:
        200:
          description: Successful login
          schema:
            type: object
            properties:
              username:
                type: string
                example: norbert@hutcake.com
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /user/account/save:
    x-swagger-router-controller: users
    post:
      tags:
        - user
      summary: Register user account
      operationId: registerAccount
      parameters:
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/UserRegister"
      responses:
        200:
          description: Successful registration
          schema:
            type: object
            properties:
              username:
                type: string
                example: norbert@hutcake.com
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /user/account/{id}/save:
    x-swagger-router-controller: users
    put:
      tags:
        - user
      summary: Update user account
      operationId: updateAccount
      parameters:
        - $ref: "#/parameters/id"
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/UserRegister"
      responses:
        200:
          description: Successful update
          schema:
            type: object
            properties:
              username:
                type: string
                example: norbert@hutcake.com
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /order/{key}:
    x-swagger-router-controller: orders
    get:
      tags:
        - order
      summary: Get items from the current order
      operationId: getOrderItems
      parameters:
        - $ref: "#/parameters/key"
      responses:
        200:
          description: Fetch all order items
          schema:
            type: object
            properties:
              id:
                type: number
                example: 10012
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /order/item:
    x-swagger-router-controller: orders
    post:
      tags:
        - order
      summary: Add an item to the order
      operationId: addOrderItem
      parameters:
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/OrderItem"
      responses:
        200:
          description: Successful created item
          schema:
            type: object
            properties:
              id:
                type: number
                example: 10012
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /order/item/{orderId}:
    x-swagger-router-controller: orders
    put:
      tags:
        - order
      summary: Update item count to the order
      operationId: updateOrderItem
      parameters:
        - $ref: "#/parameters/orderId"
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/OrderItem"
      responses:
        200:
          description: Successful updated item
          schema:
            type: object
            properties:
              id:
                type: number
                example: 10012
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
    delete:
      tags:
        - order
      summary: Add an item to the order
      operationId: removeOrderItem
      parameters:
        - $ref: "#/parameters/orderId"
      responses:
        200:
          description: Successful created item
          schema:
            type: object
            properties:
              id:
                type: number
                example: 10012
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /item:
    x-swagger-router-controller: items
    get:
      tags:
        - item
      summary: Returns 'List of items
      # used as the method name of the controller
      operationId: listItems
      parameters:
        - $ref: "#/parameters/keyword"
        - $ref: "#/parameters/category1"
        - $ref: "#/parameters/category2"
        - $ref: "#/parameters/category3"
        - $ref: "#/parameters/skip"
        - $ref: "#/parameters/limit"
        - $ref: "#/parameters/order"
        - $ref: "#/parameters/orderBy"
        - $ref: "#/parameters/type"
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              bookmark:
                type: string
                example: asdfasdfasdf213sadfasdf123
              total:
                type: number
                example: 100
              data:
                type: array
                items:
                  - $ref: "#/definitions/ItemList"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - item
      summary: create an item
      operationId: addItem
      parameters:
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/ItemCreate"
      responses:
        200:
          description: Successful created item
          schema:
            type: object
            properties:
              id:
                type: number
                example: 10012
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /item/{id}:
    x-swagger-router-controller: items
    get:
      tags:
        - item
      summary: Get item details
      operationId: previewItem
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              id:
                type: number
                example: 123445
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /category/list:
    x-swagger-router-controller: categories
    get:
      tags:
        - category
      summary: Returns structured categories
      # used as the method name of the controller
      operationId: listAllCategories
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              categories:
                type: object
                example: {}
              subCategories:
                type: object
                example: {}
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /category:
    x-swagger-router-controller: categories
    post:
      tags:
        - category
      summary: create a category
      operationId: addCategory
      parameters:
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/CategoryCreate"
      responses:
        200:
          description: Successful created item
          schema:
            type: object
            properties:
              id:
                type: number
                example: 10012
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /seller/account/{id}/view:
    x-swagger-router-controller: sellers
    get:
      tags:
        - profile
      summary: Return seller profile
      operationId: viewAccount
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Profile Object
          schema:
            properties:
              id:
                type: number
                example: 5000012
              firstName:
                type: string
                example: John
              lastName:
                type: string
                example: Stone
              dateBirthday:
                type: number
                example: 587260800000
                description: timestamp
              address1:
                type: string
                example: Upper Thompson Road
              address2:
                type: string
                example: East Cost Drive
        # 404:
        #   description: Profile not found
        #   schema:
        #     properties:
        #       message:
        #         type: string
        #         example: Not found
  /seller/account/save:
    x-swagger-router-controller: sellers
    post:
      tags:
        - seller
      summary: Register seller account
      operationId: registerAccount
      parameters:
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/UserRegister"
      responses:
        200:
          description: Successful registration
          schema:
            type: object
            properties:
              username:
                type: string
                example: norbert@hutcake.com
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /seller/account/{id}/save:
    x-swagger-router-controller: sellers
    post:
      tags:
        - seller
      summary: Update seller account
      operationId: updateAccount
      parameters:
        - $ref: "#/parameters/id"
        - name: body
          in: body
          description: post contents
          required: true
          schema:
            $ref: "#/definitions/UserRegister"
      responses:
        200:
          description: Successful registration
          schema:
            type: object
            properties:
              username:
                type: string
                example: norbert@hutcake.com
        403:
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ItemList:
    title: " "
    type: object
    properties:
      id:
        type: string
      doc:
        type: object
        description: "Item object"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UserLogin:
    title: User
    type: object
    required:
      - username
    properties:
      username:
        type: string
        description: user e-mail
  UserRegister:
    title: UserRegister
    type: object
    required:
      - email
    properties:
      email:
        type: string
        description: user e-mail
  ItemCreate:
    title: ItemCreate
    type: object
    required:
      - name
      - code
    properties:
      name:
        type: string
        description: item name
      code:
        type: number
        description: item specific code
  OrderItem:
    title: ItemOrder
    type: object
    required:
      - session_id
      - item_id
      - quantity
    properties:
      session_id:
        type: string
        description: user session id
      user_id:
        type: number
        description: user id
      item_id:
        type: number
        description: order item id
      quantity:
        type: number
        description: quantity of items
  CategoryCreate:
    title: CategoryCreate
    type: object
    required:
      - name
      - level
    properties:
      name:
        type: string
        description: category name
      level:
        type: number
        description: category level
parameters:
  # username:
  #   in: path
  #   name: username
  #   type: string
  #   required: true
  id:
    in: path
    name: id
    type: string
    required: true
  key:
    in: path
    name: id
    type: string
    required: true
  orderId:
    in: path
    name: orderId
    type: string
    required: true
  keyword:
    in: query
    name: keyword
    type: string
    required: false
  category1:
    in: query
    name: category1
    type: number
    required: false
  category2:
    in: query
    name: category2
    type: number
    required: false
  category3:
    in: query
    name: category3
    type: number
    required: false
  limit:
    in: query
    name: limit
    type: number
    required: false
  skip:
    in: query
    name: skip
    type: number
    required: false
  order:
    in: query
    name: order
    type: string
    enum:
      - asc
      - desc
    required: false
  orderBy:
    in: query
    name: orderBy
    type: string
    required: false
  type:
    in: query
    name: type
    type: string
    required: false
