CREATE TABLE grocerystore.userAccount
(id BIGINT(50) NOT NULL AUTO_INCREMENT,
username CHAR(60) NOT NULL,
password VARCHAR(250) NOT NULL,
email CHAR(100),
dateBirth BIGINT(50),
dateCreated BIGINT(50) NOT NULL,
dateUpdated BIGINT(50) NOT NULL,
uiid CHAR(150),
PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf16
